
CREATE DATABASE Aula;
USE             Aula;

CREATE TABLE CLIENTE (
	IDCLIENTE INT NOT NULL PRIMARY KEY,
    NOME      VARCHAR(60),
    ENDERECO  VARCHAR(60),
    CPF       VARCHAR(20)
);

ALTER TABLE CLIENTE ADD COLUMN TELEFONE VARCHAR(20);
ALTER TABLE CLIENTE DROP COLUMN CPF;


DROP TABLE    CLIENTE;
DROP DATABASE Aula;
