SELECT CURRENT_DATE 	 AS DATA_ATUAL;
SELECT CURRENT_TIME 	 AS HORA_ATUAL;
SELECT CURRENT_TIMESTAMP AS DATA_HORA;

SELECT EXTRACT(YEAR  FROM '2023-11-08') AS ANO;
SELECT EXTRACT(MONTH FROM '2023-11-08') AS MES;
SELECT EXTRACT(DAY   FROM '2023-11-08') AS DIA;


