
USE cidades_brasil;

SELECT * FROM CIDADE;

SELECT * FROM
	CIDADE C,
    ESTADO E
    WHERE
    C.CODIGO_ESTADO = E.CODIGO_ESTADO
    AND
    E.NOME = 'São Paulo';

SELECT C.NOME AS CIDADE,
	E.NOME AS ESTADO
	FROM CIDADE C,
	ESTADO E
	WHERE C.CODIGO_ESTADO = E.CODIGO_ESTADO
	AND E.NOME = 'Roraima';

SELECT C.NOME AS CIDADE,
	E.NOME AS ESTADO
	FROM CIDADE C,
	ESTADO E
	WHERE C.CODIGO_ESTADO = E.CODIGO_ESTADO
	AND C.NOME LIKE 'Y%';

SELECT C.NOME AS CIDADE,
	E.NOME AS ESTADO
	FROM CIDADE C,
	ESTADO E
	WHERE C.CODIGO_ESTADO = E.CODIGO_ESTADO
	AND C.NOME LIKE '%DO%';
    
SELECT C.NOME AS CIDADE,
	E.NOME AS ESTADO
	FROM CIDADE C,
	ESTADO E
	WHERE C.CODIGO_ESTADO = E.CODIGO_ESTADO
	AND C.NOME LIKE '%DAS%';

SELECT C.NOME AS CIDADE,
	E.NOME AS ESTADO
	FROM CIDADE C,
	ESTADO E
	WHERE C.CODIGO_ESTADO = E.CODIGO_ESTADO
	AND C.NOME LIKE 'C%'
    AND C.NOME LIKE '%DE%';

SELECT C.NOME AS CIDADE,
	E.NOME AS ESTADO
	FROM CIDADE C,
	ESTADO E
	WHERE C.CODIGO_ESTADO = E.CODIGO_ESTADO
	AND C.NOME LIKE '%A'
    AND C.NOME LIKE '%DE%';

SELECT C.NOME AS CIDADE,
	E.NOME AS ESTADO
	FROM CIDADE C,
	ESTADO E
	WHERE C.CODIGO_ESTADO = E.CODIGO_ESTADO
	AND (C.NOME LIKE '%DAS%' OR C.NOME LIKE '%DO%');

SELECT C.NOME AS CIDADE,
	E.NOME AS ESTADO
	FROM CIDADE C,
	ESTADO E
	WHERE C.CODIGO_ESTADO = E.CODIGO_ESTADO
	AND C.NOME NOT LIKE 'C%' /* NOT LIKE - INVERTE O SENTIDO */
    AND C.NOME LIKE '%DO%';
